# Generated by Django 4.2.2 on 2023-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheDash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationCs17',
            fields=[
                ('ma_cle_primaire', models.AutoField(primary_key=True, serialize=False)),
                ('tbl_dt', models.IntegerField(blank=True, null=True)),
                ('cs_vol', models.BigIntegerField(blank=True, db_column='CS_VOL', null=True)),
            ],
            options={
                'db_table': 'Reconciliation_CS17_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationGgsn',
            fields=[
                ('ma_cle_primaire', models.AutoField(primary_key=True, serialize=False)),
                ('tbl_dt', models.IntegerField(blank=True, null=True)),
                ('vol_data_up_to', models.BigIntegerField(blank=True, db_column='VOL_DATA_UP_TO', null=True)),
                ('vol_data_down_to', models.BigIntegerField(blank=True, db_column='VOL_DATA_DOWN_TO', null=True)),
                ('vol_data_total_to', models.BigIntegerField(blank=True, db_column='VOL_DATA_TOTAL_TO', null=True)),
            ],
            options={
                'db_table': 'Reconciliation_GGSN',
                'managed': False,
            },
        ),
    ]
