# Generated by Django 4.2.2 on 2023-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheDash', '0002_reconciliationcs17_reconciliationggsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeCs16NotInErs',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('heure', models.CharField(blank=True, db_column='HEURE', max_length=255, null=True)),
                ('sendermsisdn', models.CharField(blank=True, db_column='SENDERMSISDN', max_length=255, null=True)),
                ('dates', models.CharField(blank=True, db_column='DATES', max_length=255, null=True)),
                ('ersreference', models.CharField(blank=True, db_column='ERSREFERENCE', max_length=255, null=True)),
                ('requestamountvalue', models.CharField(blank=True, db_column='REQUESTAMOUNTVALUE', max_length=255, null=True)),
                ('receivermsisdn', models.CharField(blank=True, db_column='RECEIVERMSISDN', max_length=255, null=True)),
                ('resultcode', models.CharField(blank=True, db_column='RESULTCODE', max_length=255, null=True)),
                ('resultstatus', models.CharField(blank=True, db_column='RESULTSTATUS', max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'AIRTIME_CS16_NOT_IN_ERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirtimeCs16NotInErs2',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dateid', models.CharField(blank=True, db_column='DATEID', max_length=255, null=True)),
                ('dw_date_key', models.CharField(blank=True, db_column='DW_DATE_KEY', max_length=255, null=True)),
                ('heure', models.CharField(blank=True, db_column='HEURE', max_length=255, null=True)),
                ('extid', models.CharField(blank=True, db_column='EXTID', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, db_column='AMOUNT', max_length=255, null=True)),
                ('sendermsisdn', models.CharField(blank=True, db_column='SENDERMSISDN', max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, db_column='RECEIVER', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, db_column='HOSTNAME', max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('extid2', models.CharField(blank=True, max_length=255, null=True)),
                ('id2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'AIRTIME_CS16_NOT_IN_ERS_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BundleEwpNotInCs16',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dateid', models.CharField(blank=True, db_column='DATEID', max_length=255, null=True)),
                ('heure', models.CharField(blank=True, db_column='HEURE', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=255, null=True)),
                ('txtype', models.CharField(blank=True, db_column='TXTYPE', max_length=255, null=True)),
                ('service', models.CharField(blank=True, db_column='SERVICE', max_length=255, null=True)),
                ('fid', models.CharField(blank=True, db_column='FID', max_length=255, null=True)),
                ('ext_id', models.CharField(blank=True, db_column='EXT_ID', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, db_column='AMOUNT', max_length=255, null=True)),
                ('msisdn_from', models.CharField(blank=True, db_column='MSISDN_FROM', max_length=255, null=True)),
                ('profile_descr_fr', models.CharField(blank=True, db_column='PROFILE_DESCR_FR', max_length=255, null=True)),
                ('account_holder_cd_fr', models.CharField(blank=True, db_column='ACCOUNT_HOLDER_CD_FR', max_length=255, null=True)),
                ('type_fr', models.CharField(blank=True, db_column='TYPE_FR', max_length=255, null=True)),
                ('msisdn_to', models.CharField(blank=True, db_column='MSISDN_TO', max_length=255, null=True)),
                ('profile_descr_to', models.CharField(blank=True, db_column='PROFILE_DESCR_TO', max_length=255, null=True)),
                ('account_holder_cd_to', models.CharField(blank=True, db_column='ACCOUNT_HOLDER_CD_TO', max_length=255, null=True)),
                ('type_to', models.CharField(blank=True, db_column='TYPE_TO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'BUNDLE_EWP_NOT_IN_CS16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErsErrorAnalysis',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('datejour', models.CharField(blank=True, db_column='DATEJOUR', max_length=255, null=True)),
                ('transactiontype', models.CharField(blank=True, db_column='TRANSACTIONTYPE', max_length=255, null=True)),
                ('resultstatus', models.CharField(blank=True, db_column='RESULTSTATUS', max_length=255, null=True)),
                ('total', models.CharField(blank=True, db_column='TOTAL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ERS_ERROR_ANALYSIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EwpNotInErs',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.CharField(blank=True, max_length=255, null=True)),
                ('heure', models.CharField(blank=True, max_length=255, null=True)),
                ('fid', models.CharField(blank=True, max_length=255, null=True)),
                ('extid', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('msisdn_from', models.CharField(blank=True, max_length=255, null=True)),
                ('msisdn_to', models.CharField(blank=True, max_length=255, null=True)),
                ('finalref', models.CharField(blank=True, max_length=255, null=True)),
                ('finalstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('momodepositfailed', models.CharField(blank=True, max_length=255, null=True)),
                ('momotransactoriginalreference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EWP_NOT_IN_ERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InitialErrorPayment',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.CharField(blank=True, db_column='DATES', max_length=255, null=True)),
                ('heure', models.CharField(blank=True, db_column='HEURE', max_length=255, null=True)),
                ('txtype', models.CharField(blank=True, db_column='TXTYPE', max_length=255, null=True)),
                ('fid', models.CharField(blank=True, db_column='FID', max_length=255, null=True)),
                ('extid', models.CharField(blank=True, db_column='EXTID', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, db_column='AMOUNT', max_length=255, null=True)),
                ('sp', models.CharField(blank=True, db_column='SP', max_length=255, null=True)),
                ('msisdn_from', models.CharField(blank=True, db_column='MSISDN_FROM', max_length=255, null=True)),
                ('msisdn_to', models.CharField(blank=True, db_column='MSISDN_TO', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=255, null=True)),
                ('refund_ref', models.CharField(blank=True, db_column='REFUND_REF', max_length=255, null=True)),
            ],
            options={
                'db_table': 'INITIAL_ERROR_PAYMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeAirtimeErsCs16',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dateid', models.CharField(blank=True, db_column='DATEID', max_length=255, null=True)),
                ('ers_total', models.IntegerField(blank=True, db_column='ERS_TOTAL', null=True)),
                ('ers_amount', models.FloatField(blank=True, db_column='ERS_AMOUNT', null=True)),
                ('cs16_total', models.IntegerField(blank=True, db_column='CS16_TOTAL', null=True)),
                ('cs16_amount', models.FloatField(blank=True, db_column='CS16_AMOUNT', null=True)),
                ('gap_total', models.IntegerField(blank=True, db_column='GAP_TOTAL', null=True)),
                ('gap_amount', models.FloatField(blank=True, db_column='GAP_AMOUNT', null=True)),
            ],
            options={
                'db_table': 'RESUME_AIRTIME_ERS_CS16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeAirtimeEwpOcs',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('dateid', models.CharField(blank=True, db_column='DATEID', max_length=255, null=True)),
                ('ewp_total', models.IntegerField(blank=True, db_column='EWP_TOTAL', null=True)),
                ('ewp_amount', models.FloatField(blank=True, db_column='EWP_AMOUNT', null=True)),
                ('ocs_total', models.IntegerField(blank=True, db_column='OCS_TOTAL', null=True)),
                ('ocs_amount', models.FloatField(blank=True, db_column='OCS_AMOUNT', null=True)),
                ('gap_total', models.IntegerField(blank=True, db_column='GAP_TOTAL', null=True)),
                ('gap_amount', models.FloatField(blank=True, db_column='GAP_AMOUNT', null=True)),
            ],
            options={
                'db_table': 'RESUME_AIRTIME_EWP_OCS',
                'managed': False,
            },
        ),
    ]
